controllers:
    resource: ../../src/Controller/
    type: annotation

crud_controllers:
    resource: ../../src/Controller/CRUD/
    type: annotation
    prefix: /admin

api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api/v1

kernel:
    resource: ../../src/Kernel.php
    type: annotation
